In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4]
arr = np.array(my_list)
print(my_list)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [4]:
multi_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np.ndim(multi_arr))
print(multi_arr)
print(np.shape(multi_arr))
print(multi_arr[0:2])


2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '']]])

my_name= array[0, 2, 1] + array[1, 1, 2] + array[1, 1, 1] + array[2, 0, 1] + array[2, 0, 0] + array[0, 1, 1]
my_surname = array[2, 0, 0] + array[0, 1, 1] + array[2, 0, 1] + array[0, 2, 1] + array[1, 0, 2] + array[0, 0, 0] + array[1, 2, 2] + array[0, 1, 1]
mine = array[1, 0, 1] + array[0, 0, 0] + array[1, 1, 0] + array[1, 1, 2]
print(my_name)
print(my_surname)
print(mine)

HONTSE
SETHLARE
KAMO


In [106]:
#Slicing
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("These are the even numbers of the array:\n", array[0:3, 1:11:2])
print("\n")
print("These are the odd numbers of the array:\n", array[:3, 0:11:2])
print("\n")
print(array[:, 0:3])

These are the even numbers of the array:
 [[ 2  4]
 [ 6  8]
 [10 12]]


These are the odd numbers of the array:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [7]:
#scalar arithmetic
array = np.array([1, 2, 3, 4, 5])

print(array + 2)
print(array - 2)
print(array / 2)
print(array // 2)
print(array % 2)
print(array ** 2)
print(array * 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[1 0 1 0 1]
[ 1  4  9 16 25]
[ 2  4  6  8 10]


In [9]:
#vectorized math functions
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.sqrt(array))

radii = np.copy(array)
print(radii)
print("Radius = ", np.pi * radii ** 2)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 1  2  3  4  5  6  7  8  9 10]
Radius =  [  3.14159265  12.56637061  28.27433388  50.26548246  78.53981634
 113.09733553 153.93804003 201.06192983 254.46900494 314.15926536]


In [9]:
#Element-wise arithmetic
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 // array2)
print(array1 * array2)
print(array1 ** array2)
print(array1 % array2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[ 5 12 21 32]
[    1    64  2187 65536]
[1 2 3 4]


In [10]:
#Comparison operators
scores = np.array([81, 90, 96, 77, 92, 79])
print(scores >= 85)

[False  True  True False  True False]


In [11]:
#Broadcasting
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])
array2 = np.array([[5], [6], [7], [8]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(4, 4)
(4, 1)
[[  5  10  15  20]
 [ 30  36  42  48]
 [ 63  70  77  84]
 [104 112 120 128]]


In [12]:
#aggregate functions
array = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))# the variant
print(np.min(array))
print(np.max(array))
print(np.argmin(array))#position of the minimum value
print(np.argmax(array))#postion of the maximum value
print(np.sum(array, axis=0))#returns the sum of all columns
print(np.sum(array, axis=1))#returns sum of all rows

55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]


In [13]:
#filtering
ages = np.array([[18, 24, 17, 32, 16, 20, 19],
                 [19, 18, 15, 29, 17, 19, 18]])

teenagers = ages[ages < 18]
print(teenagers)

young_adults = ages[(ages >= 18) & (ages <29)]
print(young_adults)

seniors = ages[ages >29]
print(seniors)

adults = np.where(ages >=18, ages, 0)
print(adults)

[17 16 15 17]
[18 24 20 19 19 18 19 18]
[32]
[[18 24  0 32  0 20 19]
 [19 18  0 29  0 19 18]]


In [10]:
#generating random numbers
random_num = np.random.rand()
print(random_num)

random = np.random.random()
print(random)

0.9233722403817335
0.08726531025389894


In [15]:
#datatype objects
import numpy as np

sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int32
Data type of array 2 : float64


In [16]:
#Different ways of creating numpy arrays
# numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.
var = "Geekforgeeks"

arr = np.fromiter(var, dtype = 'U2')

print("fromiter() array :",arr)
print("\n")
#numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.
print(np.arange(1, 20 , 2, 
          dtype = np.float32))
print("\n")
#numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits. 
print(np.linspace(3.5, 10, 3, 
            dtype = np.int32))
print("\n")

#numpy.empty(): This function create a new array of given shape and type without initializing value.
print(np.empty([4, 3],
         dtype = np.int32,
         order = 'f'))
print("\n")

#numpy.ones(): This function is used to get a new array of given shape and type filled with ones (1).
np.ones([4, 3],
        dtype = np.int32,
        order = 'f')
print("\n")

# numpy.zeros(): This function is used to get a new array of given shape and type filled with zeros (0). 
np.zeros([4, 3], 
         dtype = np.int32,
         order = 'f')

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


[ 3  6 10]


[[-1232451758 -1232906318          14]
 [-2147483286         362           0]
 [-1760154912 -1232906288           1]
 [  788272461         362           0]]






array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
#attributes of ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  
print("Dimensions:", arr.ndim)  
print("Size:", arr.size) 
print("Data type:", arr.dtype)  
print("Item size:", arr.itemsize)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int32
Item size: 4


In [18]:
#Array indexing and slicing
#Basic Indexing 
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])
print("\n")

#Slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print("\n")

#multi-dimensional indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])  
print(arr_2d[0:2, 1:3])

30


[20 30 40]


6
[[2 3]
 [5 6]]


In [19]:
#Array Operations
#Matrix operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print(np.dot(matrix1, matrix2))
print("\n")

#Braodcasting
arr = np.array([[1, 2], [3, 4]])

print(arr + 10)
print("\n")

#Reshaping
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  
print(reshaped_arr)
print("\n")

#Flattening
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)

[[19 22]
 [43 50]]


[[11 12]
 [13 14]]


[[1 2 3]
 [4 5 6]]


[1 2 3 4 5 6]


In [20]:
#Numpy.eye() function
# Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)
print("\n")

# Creating a 3x5 rectangular matrix
rectangular_matrix = np.eye(3, 5)
print(rectangular_matrix)
print("\n")

# Creating a 4x4 matrix with diagonal offset
matrix = np.eye(4, k=1, dtype=np.int32)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [21]:
#Appending values at the end of an NumPy array
#Appending a Single Value to a 1D Array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)

# appending to the array
arr = np.append(arr, [6, 7, 8, 9, 10])
print('Array after appending : ', arr)

#appending another array at the end of a 1D array
arr1 = np.array([1, 2, 3])
print('First array is : ', arr1)

# creating another array
arr2 = np.array([4, 5, 6])
print('Second array is : ', arr2)

arr3 = np.array([7, 8, 9])
print('Third array is:', arr3)

# appending arr2 and arr3 to arr1
arr = np.append(arr1, [arr2, arr3])
print('Array after appending : ', arr)

#Appending Values at the End Using Concatenation
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

arr3 = np.array([2, 4, 6])
arr4 = np.array([3, 6, 9])

combined2 = np.concatenate((arr3, arr4), axis=0)
print(combined2)

#Appending with a Different Array Type
# importing the module
arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])

combined = np.append(arr, arr_float)
print(combined)  
print("\n")
#Appending Values at the End of the N-Dimensional Array
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')
# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis=0)
print('Array after appending the values column wise')
print(arr_col, '\n')

# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis=1)
print('Array after appending the values row wise')
print(arr_row)

Original Array :  [1 8 3 3 5]
Array after appending :  [ 1  8  3  3  5  6  7  8  9 10]
First array is :  [1 2 3]
Second array is :  [4 5 6]
Third array is: [7 8 9]
Array after appending :  [1 2 3 4 5 6 7 8 9]
[[1 2]
 [3 4]
 [5 6]]
[2 4 6 3 6 9]
[1. 2. 3. 4. 5.]


Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

Array to be appended column wise
[[ 5  6  7  8  9 10]]
Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array to be appended row wise
[[1]
 [2]]
Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


In [94]:
#NumPy Splitting Array
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(arr, 3)
print(array)
print("\n")

#Splitting Arrays Into Equal Parts using numpy.split()
array = np.arange(6)

# Splitting the array into 2 equal parts along the first axis (axis=0)
result = np.split(array, 2)

print("Array:")
print(array)
print("\nResult after numpy.split():")
print(result)

print("\n")

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

result1 = np.split(a, 5)
print(result1)

[array([[3, 1, 2, 0],
       [7, 5, 6, 4]]), array([[11,  9, 10,  8]]), array([[15, 13, 14, 12]])]


Array:
[0 1 2 3 4 5]

Result after numpy.split():
[array([0, 1, 2]), array([3, 4, 5])]


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [26]:
#numpy.hstack() in Python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

res = np.hstack((a, b))
print(res)

print("\n")

#Example 1: Horizontal stacking of 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

res = np.hstack((a, b))
print(res)
print("\n")
#Example 2: Stacking arrays of different shapes (raises an error)
#a = np.array([[1, 2]])
#b = np.array([[3, 4], [5, 6]])
#res = np.hstack((a, b))  Arrays must be compatabile in shape except along the concatenation axis.

#Example 3: Horizontal stacking with negative numbers
a = np.array([-1, -2, -3])
b = np.array([4, 5, 6])

res = np.hstack((a, b))
print(res)

[1 2 3 4 5 6]


[[1 2 5 6]
 [3 4 7 8]]


[-1 -2 -3  4  5  6]


In [31]:
#Example: Vertical Stacking of 1D Arrays Using numpy.vstack()
print("Horizontal Stack")
a = np.array([ 1, 2, 3] )
print ("1st Input array : \n", a) 

b = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", b) 

res = np.vstack((a, b))
print ("Output vertically stacked array:\n ", res)


print("\nVertical Stack")

#Vertical Stacking of 2D Arrays Using numpy.vstack()
a = np.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", a) 

b = np.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", b) 

res = np.vstack((a, b))
print ("Output stacked array :\n ", res)

Horizontal Stack
1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]

Vertical Stack
1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


In [59]:
#How to swap columns of a given NumPy array?
#Using indexing
a = np.arange(12).reshape(4, 3)
print("Original array:\n", a)

a[:, [0, 2]] = a[:, [2, 0]]
print("After swapping:\n",a)

print("\n")

#Using np.copy()
a = np.arange(12).reshape(4, 3)
print("Original array:\n", a)

res = a.copy()
res[:, [0, 2]] = res[:, [2, 0]]
print("After swapping:\n", res)

print("\n")

arr = np.arange(16).reshape(4, 4)
print("My array before swapping:\n", arr)
arr[:, [0,3]] = arr[:, [3, 0]]
print("After swapping:\n", arr)

Original array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping:
 [[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


Original array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping:
 [[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


My array before swapping:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After swapping:
 [[ 3  1  2  0]
 [ 7  5  6  4]
 [11  9 10  8]
 [15 13 14 12]]


In [67]:
#Joining NumPy Array
#Using numpy.concatenate()
a = np.array([1, 2])
b = np.array([3, 4])

res = np.concatenate((a, b))
print(res)
print("\n")

#Using numpy.hstack() / numpy.vstack() / numpy.dstack()
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

res_h = np.hstack((a, b))
print("np.hstack: ", res_h)

res_v = np.vstack((a, b))
print("np.vstack: ", res_v)

res_d = np.dstack((a,b))
print("np.dstack: ", res_d)
print("\n")

#Using numpy.stack()
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

res = np.stack((a, b), axis=1)
res1 = np.stack((a, b), axis=0)
print("Vertical stacked array:\n",res)
print("Horizontal stacked array:\n", res1)
print("\n")

#Using numpy.block()
b1 = np.array([[1, 1], [1, 1]])
b2 = np.array([[2, 2, 2], [2, 2, 2]])
b3 = np.array([[3, 3], [3, 3], [3, 3]])
b4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])

res = np.block([
    [b1, b2],
    [b3, b4]
])

print(res)
print("\n")

class1 = np.array([[1,1,1],[2, 2, 2]])
class2 = np.array([[3, 3, 3, 3], [4, 4, 4, 4]])
class3 = np.array([[5, 5, 5], [6, 6, 6]])
class4 = np.array([[7,7,7,7], [8, 8, 8, 8]])

combined = np.block([[class1, class2],
                    [class3, class4]])
print(combined)

[1 2 3 4]


np.hstack:  [1 2 3 4 5 6]
np.vstack:  [[1 2 3]
 [4 5 6]]
np.dstack:  [[[1 4]
  [2 5]
  [3 6]]]


Vertical stacked array:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
Horizontal stacked array:
 [[1 2 3 4]
 [5 6 7 8]]


[[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]


[[1 1 1 3 3 3 3]
 [2 2 2 4 4 4 4]
 [5 5 5 7 7 7 7]
 [6 6 6 8 8 8 8]]


In [86]:
#Combining a One and a Two-Dimensional NumPy Array
num1 = np.array([1, 2])
num2 = np.array([[10, 20],
                 [30, 40]])
                   
for a, b in np.nditer([num1, num2]):
    print(a, ":", b)
print("\n")

#Example 1: In this example, we combine a 1-D array of 5 elements with a 2-D array (2×5) 
#and display them together.
num1 = np.arange(5)
print("1D array:")
print(num1)

num2 = np.arange(10).reshape(2, 5)
print("\n2D array:")
print(num2)

# Combine 1-D and 2-D arrays
for a, b in np.nditer([num1, num2]):
    print("%d:%d" % (a, b))

print("\n")

a = np.arange(4)
b = np.arange(12).reshape(3, 4)
print("One-dimensional array:\n", a)
print("two-dimensional array:\n", b)
print("My array iteration:")
for x,y in np.nditer([a, b]):
    print(x, ":", y)

1 : 10
2 : 20
1 : 30
2 : 40


1D array:
[0 1 2 3 4]

2D array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


One-dimensional array:
 [0 1 2 3]
two-dimensional array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
My array iteration:
0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7
0 : 8
1 : 9
2 : 10
3 : 11


In [89]:
#Numpy np.ma.concatenate() method-Python
a = np.ma.array([1, 2, 3], mask=[0, 1, 0])
b = np.ma.array([4, 5, 6], mask=[0, 0, 1])

res = np.ma.concatenate([a, b])
print(res)

x = np.ma.array([2, 4, 6, 8], mask=[1, 0, 1, 0])
y = np.ma.array([3, 6, 9, 0], mask=[0, 1, 0, 1])

c = np.ma.concatenate([x, y])
print(c)

[1 -- 3 4 5 --]
[-- 4 -- 8 3 -- 9 --]


In [97]:
#Find the union of two NumPy arrays
#Using np.union1d()
a = np.array([10, 20, 30, 40])
b = np.array([20, 40, 60, 80])

res = np.union1d(a,b)
print("Using np.union1d():\n", res)
print("\n")

x = np.array([10, 20, 30, 40])
y = np.array([20, 40, 60, 80])

concat = np.concatenate((a,b))
result = np.unique(concat)
print("Using np.concatenate():\n", result)

Using np.union1d():
 [10 20 30 40 60 80]


Using np.concatenate():
 [10 20 30 40 60 80]


In [100]:
#Find unique rows in a NumPy array
#Using np.unique(axis=0)
a = np.array([[1, 2], [3, 4], [1, 2], [5, 6]])
res = np.unique(a, axis=0)
print(res)

[[1 2]
 [3 4]
 [5 6]]
